#ifndef __CONSOLAS_HPP__
#define __CONSOLAS_HPP__

// This file was generated by codegen.py

#include <array>

namespace glt {

extern std::array<char, 4194580> consolas;

} // end namespace glt

#endif // __CONSOLAS_HPP__
