#ifndef __GL_HPP__
#define __GL_HPP__

/*
 * This file solely includes the OpenGL library generated by
 * glLoadGen.  This allows the ability to use different OpenGL
 * versions (or multiple controlled by flags) without having
 * to change any other files.
 */

#ifndef GLT_OPEN_GL_MAJOR_VERSION
  #define GLT_OPEN_GL_MAJOR_VERSION 4
#endif

#ifndef GLT_OPEN_GL_MINOR_VERSION
  #define GLT_OPEN_GL_MINOR_VERSION 5
#endif

#include <glt/gl_core_4_5.hpp>

#endif // __GL_HPP__
