#ifndef __SEGOEUI_HPP__
#define __SEGOEUI_HPP__

// This file was generated by codegen.py

#include <array>

namespace glt {

extern std::array<char, 4194580> segoeui;

} // end namespace glt

#endif // __SEGOEUI_HPP__
