#ifndef __TEXTRENDER_VERT_HPP__
#define __TEXTRENDER_VERT_HPP__

// This file was generated by codegen.py
// --null set -- 0x00 is appended at the end of the array

#include <array>

namespace glt {

extern std::array<char, 267> textrender_vert;

} // end namespace glt

#endif // __TEXTRENDER_VERT_HPP__
