#ifndef __TEXTRENDER_GEOM_HPP__
#define __TEXTRENDER_GEOM_HPP__

// This file was generated by codegen.py
// --null set -- 0x00 is appended at the end of the array

#include <array>

namespace glt {

extern std::array<char, 1360> textrender_geom;

} // end namespace glt

#endif // __TEXTRENDER_GEOM_HPP__
