#ifndef __TEXTRENDER_FRAG_HPP__
#define __TEXTRENDER_FRAG_HPP__

// This file was generated by codegen.py
// --null set -- 0x00 is appended at the end of the array

#include <array>

namespace glt {

extern std::array<char, 285> textrender_frag;

} // end namespace glt

#endif // __TEXTRENDER_FRAG_HPP__
